# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebtoonRecommend' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebtoonRecommend
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
  pod 'lottie-ios'
end
